spring:
  application:
    name: FileDownloadHub
logging:
  pattern:
    console: "%date{yyyy-MM-dd HH:mm:ss.SSS} traceId:%X{traceId} [%thread] %highlight(%-5level) %logger{36} - %message%n"
  level:
    io.github: debug

springdoc:
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'file-download-hub'
      paths-to-match: '/**'
      packages-to-scan: io.github.azirzsk
  default-flat-param-object: true